require('plugins')

require('config.nvim-tree')
require('config.lsp')
require('config.cmp')
require('config.telescope')
require('config.dap')
require('config.lualine')
require('config.bufferline')
require('config.dashboard')
require('config.nvim-tree')
require('config.project')
require('config.session_manager')
require('config.theme')
require('config.treesitter')
